version: '3.8'

services:
  # 1. Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: idx-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: idx_financial_db
    ports:
      - "5432:5432"

  # 2. Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: idx-backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:${DB_PASSWORD}@db:5432/idx_financial_db"
    env_file:
      - .env
    depends_on:
      - db

  # 3. Frontend (Next.js)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: idx-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend # Frontend menunggu backend menyala dulu
